AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  slackbot

  Sample SAM Template for slackbot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  SlackbotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: mnrd_slackbot/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - arm64
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
        Cors:
          AllowCredentials: false
          AllowMethods:
            - POST
            - GET
          AllowOrigins:
            - "*"
      Policies:
        - AWSLambdaExecute
        - Statement:
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !GetAtt SlackWorkerFunction.Arn
      Environment:
        Variables:
          SLACK_BOT_TOKEN: /slackbot/bot-token
  SlackWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mnrd_slackbot/
      Runtime: python3.11
      Architectures:
        - arm64
      Handler: worker.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SLACK_BOT_TOKEN: /slackbot/bot-token


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SlackbotUrlEndpoint:
      Description: "URL of the function"
      Value:
        Fn::GetAtt: SlackbotFunctionUrl.FunctionUrl
  SlackbotFunction:
    Description: "Slackbot Lambda Function ARN"
    Value: !GetAtt SlackbotFunction.Arn
  SlackbotFunctionIamRole:
    Description: "Implicit IAM Role created for Slackbot function"
    Value: !GetAtt SlackbotFunctionRole.Arn

